ARG NODE_VERSION=22.0.0
ARG PORT=80

# Construire l'application dans une image Node
FROM node:${NODE_VERSION}-alpine as builder

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY package*.json ./
COPY public ./public
COPY src ./src

# Installer les dépendances et construire le projet
RUN npm install
RUN npm run build

# Utiliser une image NGINX pour servir l'application
FROM nginx:alpine

# Copier les fichiers de build dans le dossier de NGINX
COPY --from=builder /app/build /usr/share/nginx/html

# Copier la configuration personnalisée de NGINX
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80
EXPOSE ${PORT}

# Commande par défaut pour démarrer NGINX
CMD ["nginx", "-g", "daemon off;"]
